### ISSUE TITLE
About page with credit to artists

### ISSUE THREAD

**Issue by AlexandraBeautyman** [hayats-gryphon/wellness#127]
Could be at bottom of page. Could be its own page.

**Comment by chrismekim** [comment]
Leaf icon made by Freepik from www.flaticon.com
Flower icon made by Freepik from www.flaticon.com
Ladybug icon made by Rwida A. Kamel from www.pngtree.com
Lightning bug icon made by www.clker.com
Music and sounds by Pierre Malleret (link is https://soundcloud.com/map_composer/)

**Comment by junemie** [comment]
Golden Bee : Graphic by qubodup (link is https://www.goodfreephotos.com/) from https://www.goodfreephotos.com/
